### ISSUE TITLE
创建server时不支持key后缀的ssh key文件

### ISSUE THREAD

**Issue by cqjerry** [deskangel/DaRemote#1]
作者你好，添加服务器时无法识别key后缀的ssh key文件（比如oracle cloud）。
尝试使用PuTTYgen转换成ppk后添加，加载就报错了。

**Comment by deskangel** [comment]
您好，
key后缀的文件是什么格式的？你那边是否可以生成临时的文件发给我看下？

DaRemote支持pem格式的密钥公钥文件格式。


Best regards,
William Hsueh

cqjerry ***@***.***> 于 2022年5月21日周六 16:09写道：

**Comment by cqjerry** [comment]
[oracle_SG.zip](https://github.com/deskangel/DaRemote/files/8747393/oracle_SG.zip)
oracle默认只提供.key的文件

**Comment by deskangel** [comment]
@cqjerry  这个格式应该是支持的，你去掉扩展名即可。

**Comment by cqjerry** [comment]
好用，多谢！很棒的软件，已购买！

**Comment by cqjerry** [comment]
请问作者是否还会继续开发呢？比如增加网口流量统计等功、服务器下线通知等功能？

**Comment by deskangel** [comment]
后续版本会持续更新的，包括新的功能。

Best regards,
William Hsueh

cqjerry ***@***.***> 于 2022年5月21日周六 19:56写道：

**Comment by cqjerry** [comment]
谢谢，附件中的格式。
